### ISSUE TITLE
Multiselect existing user feilds are not visible/editable to admin or user, and even for new signups dropdown list of predefined options not displaying

### ISSUE THREAD

**Issue by ArchPrime** [procourse/discourse-multiselect-user-field#1]
Possibly this has been affected by recent Discourse update (currently on 2.5.0.beta2).
I have a multiselect dropdown feild that was previously set up and working, and set as editable after sign up etc 

![image](https://user-images.githubusercontent.com/17014496/76384896-1c233d00-63c5-11ea-9601-0bb45d804d5b.png) 

but now for existing users while contents of this field are displayed in user profile page, but field is not listed with the other editable custom user fields in user preferences page.  In other words there is no way to change.

Also, for new users signing up, while the field is visible, none of the drop down options are now available/showing (just see a slim blank blue rectangle) - meaning sign-up cannot proceed

**Comment by sudaraka94** [comment]
Hi @ArchPrime, this should have been fixed by #2 . Please check and reopen if needed.

**Comment by ArchPrime** [comment]
Hi – still not working for me.

The multiselect field is still omitted when opening any user profile.

Cheers
Paul
